    #
    # Binary DXE drivers
    # WP driver : 
    #

    FILE DRIVER = f541d663-4a48-40aa-aabf-ff158ccae34c {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/SmemDxe/SmemDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/SmemDxe/SmemDxe.efi
    SECTION UI = "SmemDxe"
    }

    FILE DRIVER = 8e9bd160-b184-11df-94e2-0800200c9a66 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/DALSys/DALSys.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/DALSys/DALSys.efi
    SECTION UI = "DALSys"
    }

    FILE DRIVER = af9763a2-033b-4109-8e17-56a98d380c92 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/HWIODxeDriver/HWIODxeDriver.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/HWIODxeDriver/HWIODxeDriver.efi
    SECTION UI = "HWIODxeDriver"
    }

    FILE DRIVER = 10e193df-9966-44e7-b17c-59dd831e20fc {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/ChipInfo/ChipInfo.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/ChipInfo/ChipInfo.efi
    SECTION UI = "ChipInfo"
    }

    FILE DRIVER = b105211b-bbbd-4add-a3b0-d1cf4a52154c {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/PlatformInfoDxeDriver/PlatformInfoDxeDriver.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/PlatformInfoDxeDriver/PlatformInfoDxeDriver.efi
    SECTION UI = "PlatformInfoDxeDriver"
    }

    FILE DRIVER = 7942a7eb-b7d5-4e2e-b908-831e4de55b58 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/GlinkDxe/GlinkDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/GlinkDxe/GlinkDxe.efi
    SECTION UI = "GlinkDxe"
    }

    FILE DRIVER = e43128a8-8692-42b6-8afa-676158578d18 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/ULogDxe/ULogDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/ULogDxe/ULogDxe.efi
    SECTION UI = "ULogDxe"
    }

    FILE DRIVER = cb29f4d1-7f37-4692-a416-93e82e219711 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/NpaDxe/NpaDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/NpaDxe/NpaDxe.efi
    SECTION UI = "NpaDxe"
    }

    FILE DRIVER = 4db5dea6-5302-4d1a-8a82-677a683b0d29 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/ClockDxe/ClockDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/ClockDxe/ClockDxe.efi
    SECTION UI = "ClockDxe"
    }

    FILE DRIVER = 0d35cd8e-97ea-4f9a-96af-0f0d89f76567 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/UFSDxe/UFSDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/UFSDxe/UFSDxe.efi
    SECTION UI = "UFSDxe"
    }

    FILE DRIVER = 8681cc5a-0df6-441e-b4b8-e915c538f067 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/DALTLMM/DALTLMM.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/DALTLMM/DALTLMM.efi
    SECTION UI = "DALTLMM"
    }

    FILE DRIVER = 2a7b4bef-80cd-49e1-b473-374ba4d673fc {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/SPMI/SPMI.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/SPMI/SPMI.efi
    SECTION UI = "SPMI"
    }

    FILE DRIVER = F10F76DB-42C1-533F-34A8-69BE24653110 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/SdccDxe/SdccDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/SdccDxe/SdccDxe.efi
    SECTION UI = "SdccDxe"
    }

    FILE DRIVER = C44697D5-B4AA-4030-9749-29860844183D {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/PmicDxe/PmicDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/PmicDxe/PmicDxe.efi
    SECTION UI = "PmicDxe"
    }

    FILE DRIVER = 7a32bd23-f735-4f57-aa1a-447d2fe3be0d {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/SPI/SPI.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/SPI/SPI.efi
    SECTION UI = "SPI"
    }

    FILE DRIVER = 04de8591-d2b3-4077-bbbe-b12070094eb6 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/I2C/I2C.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/I2C/I2C.efi
    SECTION UI = "I2C"
    }

    FILE DRIVER = 5A5CB8CA-9382-4E0C-B383-77FB517CD9EB {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/AdcDxe/AdcDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/AdcDxe/AdcDxe.efi
    SECTION UI = "AdcDxe"
    }

    FILE DRIVER = 88ABF42E-EFA7-4D72-A9C8-8B29ACDCF64F {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/MpPowerDxe/MpPowerDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/MpPowerDxe/MpPowerDxe.efi
    SECTION UI = "MpPowerDxe"
    }

# WP USB

    FILE DRIVER = DD0616C8-B50D-4A58-B9BE-10C9F3F7156C {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/UsbTypeCDxe/UsbTypeCDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/UsbTypeCDxe/UsbTypeCDxe.efi
    SECTION UI = "UsbTypeCDxe"
    }

    FILE DRIVER = 94F8A6A7-DC34-4101-88C1-99179CCEAE83 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/UsbfnDwc3Dxe/UsbfnDwc3Dxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/UsbfnDwc3Dxe/UsbfnDwc3Dxe.efi
    SECTION UI = "UsbfnDwc3Dxe"
    }

    FILE DRIVER = BEB12BEE-F6E1-11E1-9FB8-6C626DE4AEB1 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/XhciPciEmulation/XhciPciEmulation.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/XhciPciEmulation/XhciPciEmulation.efi
    SECTION UI = "XhciPciEmulation"
    }

    FILE DRIVER = B7F50E91-A759-412C-ADE4-DCD03E7F7C28 {
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/XhciDxe/XhciDxe.efi
    SECTION UI = "XhciDxe"
    }

    FILE DRIVER = 2D2E62CF-9ECF-43B7-8219-94E7FC713DFE {
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/UsbKbDxe/UsbKbDxe.efi
    SECTION UI = "UsbKbDxe"
    }

    FILE DRIVER = 5AF77F10-90DF-4E7E-8325-A17EC09D5443 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/UsbMsdDxe/UsbMsdDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/UsbMsdDxe/UsbMsdDxe.efi
    SECTION UI = "UsbMsdDxe"
    }

    # wp
    FILE DRIVER = 3299A266-15F0-4346-8318-716336736D3E {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/UsbDeviceDxe/UsbDeviceDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/UsbDeviceDxe/UsbDeviceDxe.efi
    SECTION UI = "UsbDeviceDxe"
    }

    FILE DRIVER = CD823A4D-7DEC-4531-AE5D-4134FA4127B8 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/UsbConfigDxe/UsbConfigDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/UsbConfigDxe/UsbConfigDxe.efi
    SECTION UI = "UsbConfigDxe"
    }

    FILE DRIVER = 0A134F0E-075E-40B3-9C63-3B3906804663 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/UsbInitDxe/UsbInitDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/UsbInitDxe/UsbInitDxe.efi
    SECTION UI = "UsbInitDxe"
    }

    FILE DRIVER = 51D4273A-C3FB-48FD-B5B7-97CE091A58A6 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/UsbfnChgDxe/UsbfnChgDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/UsbfnChgDxe/UsbfnChgDxe.efi
    SECTION UI = "UsbfnChgDxe"
    }

    FILE DRIVER = 2D2E62AA-9ECF-43B7-8219-94E7FC713DFE {
    SECTION PE32 = MSM8998Pkg/Devices_Binary/wp/UsbMouseDxe/UsbMouseDxe.efi
    SECTION UI = "UsbMouseDxe"
    }

    FILE DRIVER = 5bd181db-0487-4f1a-ae73-820e165611b3 {
    SECTION DXE_DEPEX = MSM8998Pkg/Devices_Binary/wp/ButtonsDxe/ButtonsDxe.depex
    SECTION PE32 = MSM8998Pkg/Devices_Binary/joan/ButtonsDxe/ButtonsDxe.efi
    SECTION UI = "ButtonsDxe"
    }

    # FILE DRIVER = 9A5163E7-5C29-453F-825C-837A46A81E15 {
    # SECTION DXE_DEPEX = MSM8998Pkg/Binary/SerialDxe/SerialDxe.depex
    # SECTION PE32 = MSM8998Pkg/Binary/SerialDxe/SerialDxe.efi
    # SECTION UI = "SerialDxe"
    # } 